---
version: '3.2'
services:
  gitserver:
    image: quay.io/derektamsen/docker-gitserver
    build: ./
    read_only: true
    restart: on-failure:5
    ports:
      - "2222:22"
    volumes:
      - data-nfs:/data
    environment:
      - SSH_KEY="${GITSERVER_SSH_KEY}"
      - SSH_ADMIN="${GITSERVER_SSH_ADMIN}"
volumes:
  data-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_DATA}"
