apiVersion: v1
kind: Service
metadata:
  name: gitserver-svc
spec:
  type: NodePort
  selector:
    app: gitserver
  ports:
  - port: 22
    nodePort: 32222
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitserver-pvc
  labels:
    app: gitserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitserver
  template:
    metadata:
      labels:
        app: gitserver
    spec:
      containers:
      - name: gitolite
        image: quay.io/derektamsen/docker-gitserver:latest
        env:
        - name: SSH_KEY
          valueFrom:
            configMapKeyRef:
              name: gitserver-config
              key: ssh.key
        - name: SSH_ADMIN
          valueFrom:
            configMapKeyRef:
              name: gitserver-config
              key: ssh.admin
        ports:
        - containerPort: 22
        volumeMounts:
        - name: gitserver-ps
          mountPath: /data
      volumes:
        - name: gitserver-ps
          persistentVolumeClaim:
            claimName: gitserver-pvc
