#!/usr/bin/env bash

echo 'Starting the data container...'
sudo docker run --memory 512m --cpu-shares 512 -v /data \
  --name gitserver-data derektamsen/gitserver-data

echo 'Starting the service container...'
sudo docker run -d --restart on-failure:5 --publish 2222:22 --memory 512m \
  --cpu-shares 512 --read-only --volumes-from gitserver-data \
  -e SSH_KEY="$(cat ~/.ssh/id_rsa.pub)" \
  -e SSH_ADMIN="${USER}" \
  --name gitserver derektamsen/gitserver
